:set background=dark
:syntax off
:syntax on
set ruler
set nocompatible
filetype plugin indent on
set mouse=a
set incsearch
set hlsearch

set foldmethod=syntax

runtime! macros/matchit.vim

augroup myfiletypes
	autocmd!
	autocmd FileType ruby,eruby,yaml set ai sw=2 sts=2 et
	autocmd FileType c,php set ai sw=4 sts=4 et
augroup END

augroup markdown
	au! BufRead,BufNewFile *.mkd setfiletype mkd 
	au! BufRead,BufNewFile *.mkd set tw=100
augroup END

augroup mkd
	autocmd BufRead *.mkd  set ai formatoptions=tcroqn2 comments=n:>
augroup END

au bufNewFile *.c 0r ~/.vim/templates/tpl.c
au bufNewFile *.h 0r ~/.vim/templates/tpl.h

" La correction orthographique, c'est très très bien
map ,C :w<CR>:!aspell -c %<CR>:e %<CR>
